workflows: fixes to make author dags work
inspirehep/workflows pull request #3
Opened 2024-07-01 09:40 UTC by DonHaul

2024-07-08 08:03 UTC, drjova commented on dags/author/author_create/author_create_approved.py
> +            "name": {"value": "PlaceHolder"},
why do we need a placeholder?

2024-07-08 08:04 UTC, drjova commented on dags/author/author_create/author_create_approved.py
> +            "$schema": "http://inspirebeta.net/schemas/records/authors.json",
```suggestion
            "$schema": "http://inspirehep.net/schemas/records/authors.json",
```

2024-07-08 08:05 UTC, drjova requested changes
Thank you, I have added some comments

2024-07-08 08:05 UTC, drjova commented on dags/author/author_create/author_create_approved.py
> +        )
I don't think we need this

2024-07-08 08:37 UTC, DonHaul commented on dags/author/author_create/author_create_approved.py
> +        )
Removed

2024-07-08 08:38 UTC, DonHaul commented on dags/author/author_create/author_create_approved.py
> +            "name": {"value": "PlaceHolder"},
According to the name property must have a value, it must be a non empty string

2024-07-08 11:04 UTC, drjova requested changes
Thank you, two small comments

2024-07-08 11:04 UTC, drjova commented on dags/author/author_create/author_create_approved.py
> +        """sets status to running"""
we don't need this docstring

2024-07-08 11:04 UTC, drjova commented on dags/author/author_create/author_create_approved.py
> +            "name": {"value": "NAME"},
Why do we need that?

2024-07-08 12:30 UTC, drjova commented on plugins/hooks/backoffice/workflow_ticket_management_hook.py
> +        endpoint = "api/workflow-ticket/"
are you sure we don't need the `/` in the beginning?

2024-07-08 14:19 UTC, DonHaul commented on plugins/hooks/backoffice/workflow_ticket_management_hook.py
> +        endpoint = "api/workflow-ticket/"
Currently the hook handles it for use if there is no `/`
https://github.com/inspirehep/workflows/blob/main/plugins/hooks/backoffice/base.py#L49
If it makes it more clear I can explicitly add it to every endpoint

2024-07-08 14:20 UTC, drjova approved these changes

2024-07-08 14:21 UTC, drjova commented
@DonHaul could you please squash?

2024-07-08 15:30 UTC, DonHaul commented
@drjova could you give me write access? I cant seem to merge

2024-07-09 06:53 UTC, drjova commented
@DonHaul could you please rebase?

2024-07-10 11:30 UTC, drjova approved these changes

2024-07-10 11:31 UTC, merged